{% set version = "0.0.5" %}

package:
  name: docdata
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/docdata/docdata-{{ version }}.tar.gz
  sha256: ff3b963ab3f8b47476891fa01796828f8b16b10d6605e731690c5e1b5d3e0683

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - docdata
  commands:
    - pip check

about:
  home: https://github.com/cthoyt/docdata
  summary: Add structured information to the end of your python docstrings.
  license: MIT
  license_file: LICENSE
  doc_url: https://docdata.readthedocs.io
  dev_url: https://github.com/cthoyt/docdata

extra:
  recipe-maintainers:
    - jamesmyatt
